### ISSUE TITLE
Helm chart ignores `tag` from values file

### ISSUE THREAD

**Issue by javydekoning** [openspeedtest/Helm-chart#4]
The current helm chart ignores the tag from `values.yaml`

Your template needs to be changed to:

```yaml
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ printf "%s:%s" .Values.image.repository (default .Chart.AppVersion .Values.image.tag) | quote }}"
```

However, note that this would currently break you helm chart because the current `AppVersion` is `1.16.0` but that tag doesn't exist on Dockerhub.
